version: '3.9'

services:
  web:
    image: node
    container_name: vue_intro
    tty: true
    stdin_open: true
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - 3000:3000
      - 8000:8000